### PR TITLE
Base startup scripts use systemd and verify growth of base_log...ubx file.

### PR DESCRIPTION
**Pull request by ivangayton**
Lots going on here!

### Context
We're working on PPK here in Tanzania. So most of this is squarely aimed at getting high-quality static PPK points. Iddy and I are working on this in real-time as we survey Ground Control Points for the World Bank river drone mapping project. 

### Scripts checking log file growth
The scripts on the raspberry pis were starting up, sometimes creating log files (```base_log_datetime_.ubx```) and streaming when there wasn't actually data coming from the Ardusimple for whatever reason. This required surveyors to ssh into the Pis to verify that the log file was growing. To address this, I modified the base startup script to:
- Check for a USB or UART device
- Attempt to launch a log file
- Check that the log file is actually growing, then stand by

### Startup mechanism from cron to systemd
Also, the startup scripts were being launched by cron (using ```@reboot```). That's fine, but I wanted more control over the exact moment of startup, and to improve error logging for debugging both in the field and for development. So I created systemd service files (```gnss_base.service``` and ```gnss_rover.service```). Those launch on startup quite reliably, and output to both a ```log.txt``` and ```error.log``` file in the ```/home/pi``` directory. To use these, you still have to put them in the ```/etc/systemd/system/``` folder and instruct systemd to fire them up on startup with ```sudo systemctl enable gnss_base.service``` (or the corresponding one for the rover, which is slightly different because the output filename and baud rate is different). I'll create image files for both rover and base with that stuff already done after we've done some field testing and worked out the kinks.

### Stub of welcoming Readme
Finally, I added a nice photo of a happy Tanzanian surveyor using the stuff to the main Readme, which I'd like to eventually turn into a nice welcome page with general information and guidance how to use the various resources here (I expect there will be people of varying levels of sophistication trying to use this stuff, and a nice welcome page won't be amiss).

### CODE REVIEW

**Comment by kriete** [comment]
Hi Ivan,

thanks a lot for reworking these very nasty startup scripts! I totally agree that they have to be changed to work more seamlessly.
I did not test your scripts yet. But from what I've seen from the code it is much more stable now. Very good idea to check the file growth and checking for input data.
I guess we could already merge it but anyway I hope that I have the time this weekend and will just check the scripts by trying them out once! If I run into any problems, I will let you know or try to fix them on my own :)

By the way, I just added a paragraph in the documentation about using only your smartphone connected to the ardusimple as a rover. You can directly get an RTK solution and log points / tracks  with it using an NTRIP client. This removes the necessity of the raspberry pi in between. Downside is that it is not possible to mock your GPS position with it but may be a good solution if the rover raspberry pi is striking by whatever reason.

Also, I reworked the post-processing part. Now Multi-GNSS post-processing should be covered and I also included an example configuration!

**Comment by ivangayton** [comment]
Hi Andreas, awesome, thanks for continuing to work on this and share your brilliance with us! Especially grateful for more work on multi-GNSS post-processing.

If you might be testing this weekend, I'll try to add more instructions before then. Specifically to make sure the Systemd setup is clear. Ultimately I want to package this whole setup as a .set of deb archives so you can just install gnss_baae.deb or gnss_rover.deb and the whole thing will install and automatically activate on startup, but for now we still have to manually set up the systemd service.

**Comment by kriete** [comment]
I tested the scripts on Saturday and it works as you described it. Well done and well documented!

It works very good as logging the data via USB. For streaming purposes, I had to add and modify the script of course a bit. Also one should be aware if the logging is performed via UART (jumper cables) the access restrictions may be a problem (ttyS0 may belong to root) and the scripts are executed from the user pi in this case.

I have a python script that splits the incoming data stream from USB into RTCM3 and UBX/NMEA messages. This way, no jumper cables are required for a base station. I should make a new image soon with a ready-to-use configuration...

**Comment by ivangayton** [comment]
Awesome!!

At some point we should think about creating a .deb package instead of
images; it would be a lot smaller to store and easier to update.

A .deb package allows you to take a stock Raspbian (or any Debian-based
distro) and add this kind of functionality with apt or dpkg (for example
sudo apt install rtk_gnss). It adds files into all of the relevant
directories and then runs a script—so you can easily set up a systemd
service or whatever.

Andreas, if you are interested we have some funding for work in DRC that I
could maybe take some of to hire you for some consulting days to work on
this (at a proper professional rate). Interested?

Onward,
Ivan

**Pull request merged**
