### PR TITLE
Ardusimple_setup_for_student_projects.md: formatting and syntax improvments

### PR DESCRIPTION
**Pull request by vazhnov**
* Formatting improved
* Typos fixed
* Newlines added to split too big chapters

### CODE REVIEW

**Comment by vazhnov** [comment]
@hcwinsemius , could you please merge this?

**Comment by hcwinsemius** [comment]
Looks good. Thanks! I'd love to know what you are working on so that we can keep contact or point you towards other devs.

**Comment by vazhnov** [comment]
@hcwinsemius , thank you for this project with opensource license!

I'm thinking to buy some module based on ZED-F9P or ZED-F9K for better GPX tracks for OpenStreetMap. I started this topic here: https://forum.openstreetmap.org/viewtopic.php?id=71718

Maybe in future I will add 360° camera to create high-quality pictures for Mapillary.

**Comment by ivangayton** [comment]
@vazhnov thanks for this! We're delighted to include your contributions. Keep us posted on your activities and plans. 

If you are interested in 360° cams, we (same team, including @hcwinsemius and I, along with Stever Mather) are working on [this](https://github.com/localdevices/odm360)

**Pull request merged**
